// Code generated by "stringer -type execType -trimprefix exec"; DO NOT EDIT.

package main

import "strconv"

const _execType_name = "BootstrapCorpusMinimizeInputMinimizeCrasherTriageInputFuzzVersifierSmashSonarSonarHintTotalCount"

var _execType_index = [...]uint8{0, 9, 15, 28, 43, 54, 58, 67, 72, 77, 86, 91, 96}

func (i execType) String() string {
	if i >= execType(len(_execType_index)-1) {
		return "execType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _execType_name[_execType_index[i]:_execType_index[i+1]]
}
