// Copyright 2015 Dmitry Vyukov. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

// Code generated by protoc-gen-go.
// source: examples/protobuf/pb/gen.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	examples/protobuf/pb/gen.proto

It has these top-level messages:
	M0
	M1
	M2
	M3
	M4
	M5
	M6
	M7
	M8
	M9
	M10
	M11
	M12
	M13
	M14
	M15
	M16
	M17
	M18
	M19
	M20
	M21
	M22
	M23
	M24
	M25
*/
package example

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Corpus int32

const (
	Corpus_UNIVERSAL Corpus = 0
	Corpus_WEB       Corpus = 1
	Corpus_IMAGES    Corpus = 2
	Corpus_LOCAL     Corpus = 42
	Corpus_NEWS      Corpus = 155
	Corpus_PRODUCTS  Corpus = 123123
)

var Corpus_name = map[int32]string{
	0:      "UNIVERSAL",
	1:      "WEB",
	2:      "IMAGES",
	42:     "LOCAL",
	155:    "NEWS",
	123123: "PRODUCTS",
}
var Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     42,
	"NEWS":      155,
	"PRODUCTS":  123123,
}

func (x Corpus) Enum() *Corpus {
	p := new(Corpus)
	*p = x
	return p
}
func (x Corpus) String() string {
	return proto.EnumName(Corpus_name, int32(x))
}
func (x *Corpus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Corpus_value, data, "Corpus")
	if err != nil {
		return err
	}
	*x = Corpus(value)
	return nil
}

type M0 struct {
	F                *int32 `protobuf:"varint,1,req,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M0) Reset()         { *m = M0{} }
func (m *M0) String() string { return proto.CompactTextString(m) }
func (*M0) ProtoMessage()    {}

func (m *M0) GetF() int32 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M1 struct {
	F                *int64 `protobuf:"varint,1,req,name=f,def=-123123123123" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M1) Reset()         { *m = M1{} }
func (m *M1) String() string { return proto.CompactTextString(m) }
func (*M1) ProtoMessage()    {}

const Default_M1_F int64 = -123123123123

func (m *M1) GetF() int64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return Default_M1_F
}

type M2 struct {
	F                *uint32 `protobuf:"varint,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M2) Reset()         { *m = M2{} }
func (m *M2) String() string { return proto.CompactTextString(m) }
func (*M2) ProtoMessage()    {}

func (m *M2) GetF() uint32 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M3 struct {
	F                *uint64 `protobuf:"varint,1,opt,name=f,def=123123123123" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M3) Reset()         { *m = M3{} }
func (m *M3) String() string { return proto.CompactTextString(m) }
func (*M3) ProtoMessage()    {}

const Default_M3_F uint64 = 123123123123

func (m *M3) GetF() uint64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return Default_M3_F
}

type M4 struct {
	F                *int32 `protobuf:"zigzag32,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M4) Reset()         { *m = M4{} }
func (m *M4) String() string { return proto.CompactTextString(m) }
func (*M4) ProtoMessage()    {}

func (m *M4) GetF() int32 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M5 struct {
	F                *int64 `protobuf:"zigzag64,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M5) Reset()         { *m = M5{} }
func (m *M5) String() string { return proto.CompactTextString(m) }
func (*M5) ProtoMessage()    {}

func (m *M5) GetF() int64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M6 struct {
	F                *uint32 `protobuf:"fixed32,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M6) Reset()         { *m = M6{} }
func (m *M6) String() string { return proto.CompactTextString(m) }
func (*M6) ProtoMessage()    {}

func (m *M6) GetF() uint32 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M7 struct {
	F                *uint64 `protobuf:"fixed64,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M7) Reset()         { *m = M7{} }
func (m *M7) String() string { return proto.CompactTextString(m) }
func (*M7) ProtoMessage()    {}

func (m *M7) GetF() uint64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M8 struct {
	F                *int32 `protobuf:"fixed32,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M8) Reset()         { *m = M8{} }
func (m *M8) String() string { return proto.CompactTextString(m) }
func (*M8) ProtoMessage()    {}

func (m *M8) GetF() int32 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M9 struct {
	F                *int64 `protobuf:"fixed64,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M9) Reset()         { *m = M9{} }
func (m *M9) String() string { return proto.CompactTextString(m) }
func (*M9) ProtoMessage()    {}

func (m *M9) GetF() int64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M10 struct {
	F                *float64 `protobuf:"fixed64,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *M10) Reset()         { *m = M10{} }
func (m *M10) String() string { return proto.CompactTextString(m) }
func (*M10) ProtoMessage()    {}

func (m *M10) GetF() float64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M11 struct {
	F                *float32 `protobuf:"fixed32,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *M11) Reset()         { *m = M11{} }
func (m *M11) String() string { return proto.CompactTextString(m) }
func (*M11) ProtoMessage()    {}

func (m *M11) GetF() float32 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

type M12 struct {
	F                *bool  `protobuf:"varint,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M12) Reset()         { *m = M12{} }
func (m *M12) String() string { return proto.CompactTextString(m) }
func (*M12) ProtoMessage()    {}

func (m *M12) GetF() bool {
	if m != nil && m.F != nil {
		return *m.F
	}
	return false
}

type M13 struct {
	F                *string `protobuf:"bytes,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M13) Reset()         { *m = M13{} }
func (m *M13) String() string { return proto.CompactTextString(m) }
func (*M13) ProtoMessage()    {}

func (m *M13) GetF() string {
	if m != nil && m.F != nil {
		return *m.F
	}
	return ""
}

type M14 struct {
	F                []byte `protobuf:"bytes,1,opt,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M14) Reset()         { *m = M14{} }
func (m *M14) String() string { return proto.CompactTextString(m) }
func (*M14) ProtoMessage()    {}

func (m *M14) GetF() []byte {
	if m != nil {
		return m.F
	}
	return nil
}

type M15 struct {
	F0               *int32  `protobuf:"varint,1,req,name=f0" json:"f0,omitempty"`
	F1               *string `protobuf:"bytes,2,opt,name=f1" json:"f1,omitempty"`
	F2               []byte  `protobuf:"bytes,3,opt,name=f2" json:"f2,omitempty"`
	F4               *bool   `protobuf:"varint,5,opt,name=f4" json:"f4,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M15) Reset()         { *m = M15{} }
func (m *M15) String() string { return proto.CompactTextString(m) }
func (*M15) ProtoMessage()    {}

func (m *M15) GetF0() int32 {
	if m != nil && m.F0 != nil {
		return *m.F0
	}
	return 0
}

func (m *M15) GetF1() string {
	if m != nil && m.F1 != nil {
		return *m.F1
	}
	return ""
}

func (m *M15) GetF2() []byte {
	if m != nil {
		return m.F2
	}
	return nil
}

func (m *M15) GetF4() bool {
	if m != nil && m.F4 != nil {
		return *m.F4
	}
	return false
}

type M16 struct {
	F                *Corpus `protobuf:"varint,1,opt,name=f,enum=example.Corpus,def=0" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M16) Reset()         { *m = M16{} }
func (m *M16) String() string { return proto.CompactTextString(m) }
func (*M16) ProtoMessage()    {}

const Default_M16_F Corpus = Corpus_UNIVERSAL

func (m *M16) GetF() Corpus {
	if m != nil && m.F != nil {
		return *m.F
	}
	return Default_M16_F
}

type M17 struct {
	F                *M15   `protobuf:"bytes,1,req,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M17) Reset()         { *m = M17{} }
func (m *M17) String() string { return proto.CompactTextString(m) }
func (*M17) ProtoMessage()    {}

func (m *M17) GetF() *M15 {
	if m != nil {
		return m.F
	}
	return nil
}

type M18 struct {
	F0               *string                   `protobuf:"bytes,1,opt,name=f0" json:"f0,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *M18) Reset()         { *m = M18{} }
func (m *M18) String() string { return proto.CompactTextString(m) }
func (*M18) ProtoMessage()    {}

var extRange_M18 = []proto.ExtensionRange{
	{100, 199},
}

func (*M18) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_M18
}
func (m *M18) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *M18) GetF0() string {
	if m != nil && m.F0 != nil {
		return *m.F0
	}
	return ""
}

type M19 struct {
	F                []int32 `protobuf:"varint,1,rep,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M19) Reset()         { *m = M19{} }
func (m *M19) String() string { return proto.CompactTextString(m) }
func (*M19) ProtoMessage()    {}

func (m *M19) GetF() []int32 {
	if m != nil {
		return m.F
	}
	return nil
}

type M20 struct {
	F                []string `protobuf:"bytes,1,rep,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *M20) Reset()         { *m = M20{} }
func (m *M20) String() string { return proto.CompactTextString(m) }
func (*M20) ProtoMessage()    {}

func (m *M20) GetF() []string {
	if m != nil {
		return m.F
	}
	return nil
}

type M21 struct {
	F                []*M15 `protobuf:"bytes,1,rep,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M21) Reset()         { *m = M21{} }
func (m *M21) String() string { return proto.CompactTextString(m) }
func (*M21) ProtoMessage()    {}

func (m *M21) GetF() []*M15 {
	if m != nil {
		return m.F
	}
	return nil
}

type M22 struct {
	F                []*M2  `protobuf:"bytes,1,rep,name=f" json:"f,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *M22) Reset()         { *m = M22{} }
func (m *M22) String() string { return proto.CompactTextString(m) }
func (*M22) ProtoMessage()    {}

func (m *M22) GetF() []*M2 {
	if m != nil {
		return m.F
	}
	return nil
}

type M23 struct {
	F                map[int32]string `protobuf:"bytes,1,rep,name=f" json:"f,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *M23) Reset()         { *m = M23{} }
func (m *M23) String() string { return proto.CompactTextString(m) }
func (*M23) ProtoMessage()    {}

func (m *M23) GetF() map[int32]string {
	if m != nil {
		return m.F
	}
	return nil
}

type M24 struct {
	F                map[string]*M2 `protobuf:"bytes,1,rep,name=f" json:"f,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *M24) Reset()         { *m = M24{} }
func (m *M24) String() string { return proto.CompactTextString(m) }
func (*M24) ProtoMessage()    {}

func (m *M24) GetF() map[string]*M2 {
	if m != nil {
		return m.F
	}
	return nil
}

type M25 struct {
	F0               *string `protobuf:"bytes,4,opt,name=f0" json:"f0,omitempty"`
	F1               *M2     `protobuf:"bytes,9,opt,name=f1" json:"f1,omitempty"`
	F2               *Corpus `protobuf:"varint,127,opt,name=f2,enum=example.Corpus" json:"f2,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *M25) Reset()         { *m = M25{} }
func (m *M25) String() string { return proto.CompactTextString(m) }
func (*M25) ProtoMessage()    {}

func (m *M25) GetF0() string {
	if m != nil && m.F0 != nil {
		return *m.F0
	}
	return ""
}

func (m *M25) GetF1() *M2 {
	if m != nil {
		return m.F1
	}
	return nil
}

func (m *M25) GetF2() Corpus {
	if m != nil && m.F2 != nil {
		return *m.F2
	}
	return Corpus_UNIVERSAL
}

var E_F1 = &proto.ExtensionDesc{
	ExtendedType:  (*M18)(nil),
	ExtensionType: (*int32)(nil),
	Field:         126,
	Name:          "example.f1",
	Tag:           "varint,126,opt,name=f1",
}

func init() {
	proto.RegisterEnum("example.Corpus", Corpus_name, Corpus_value)
	proto.RegisterExtension(E_F1)
}
