// Copyright 2015 go-fuzz project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

// +build gofuzz
// +build gofuzz_libfuzzer

package gofuzzdep

import (
	"unsafe"

	. "github.com/dvyukov/go-fuzz/go-fuzz-defs"
)

// Bool is just a bool.
// It is used by code autogenerated by go-fuzz-build
// to avoid compilation errors when a user's code shadows the built-in bool.
type Bool = bool

var (
	CoverTab    *[CoverSize]byte
	sonarRegion []byte
	sonarPos    uint32
	CoverTabTmp [CoverSize]byte
)

func init() {
	CoverTab = (*[CoverSize]byte)(unsafe.Pointer(&CoverTabTmp[0]))
}

func Initialize(coverTabPtr unsafe.Pointer, coverTabSize uint64) {
	if coverTabSize != CoverSize {
		panic("Incorrect cover tab size")
	}
	CoverTab = (*[CoverSize]byte)(coverTabPtr)
}

func Main(f func([]byte) int) {
}
