// Copyright 2015 go-fuzz project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

// Package types provides types and data shared between go-fuzz-build and go-fuzz.
package types

// Version is an opaque identifier describing the zip file
// generated by go-fuzz-build and consumed by go-fuzz.
// It should be altered to a never-before-used value
// any time you make a change that could cause a zip file
// generated by go-fuzz-build not to be fully interoperable
// with a different version of go-fuzz.
const Version = "1"

type CoverBlock struct {
	ID        int
	File      string
	StartLine int
	StartCol  int
	EndLine   int
	EndCol    int
	NumStmt   int
}

type Literal struct {
	Val   string
	IsStr bool
}

type MetaData struct {
	Literals    []Literal
	Blocks      []CoverBlock
	Sonar       []CoverBlock
	Funcs       []string // fuzz function names; must have length > 0
	DefaultFunc string   // default function to fuzz
}
